<?php

namespace app\user\controller;

use think\Controller;
use think\Db;
use app\user\model\News;
use think\Log;
use My\RedisPackage;

class App extends Controller
{

    public function _initialize()
    {
        //       parent::_initialize(); // TODO: Change the autogenerated stub
        $this->cross();
    }

    public function cross()
    {
        header('Access-Control-Allow-Origin:*');
        header('Access-Control-Allow-Methods:GET,POST,PATCH,PUT,OPTIONS');

        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: POST,GET,OPTIONS');
        header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
    }

    //根据类型,分页获取新闻，
    //{"type":1,"page",1}
    public function getNews()
    {
//        extension_loaded('redis');
//        $redis = new \Redis();
//        $redis->connect('127.0.0.1', 6379);
//        $redis->set('test', 'hello redis');
//        $name = $redis->get('name');

//        $redis = RedisPackage::getInstance();
//        $name = $redis::get('name');



        $json = file_get_contents("php://input");
        Log::write('post data' . $json, 'notice');
        Log::save();
        $arrary = json_decode($json, true);
        $type = $arrary['type'];
        $page = $arrary['page'];
        $start = ($page - 1) * 5;
        Log::write('-----' . $type, 'notice');
        if ($type == 0) {
            Log::write('go all type', 'notice');
            $data = Db::table('news')->limit($start, 5)->select();
            return ['data' => $data, 'code' => 1, 'message' => 'success'];
        } else {
            $data = Db::table('news')->where('type', $type)->limit($start, 5)->select();
            return ['data' => $data, 'code' => 1, 'message' => 'success'];
        }

    }

    public function getAllNews()
    {
        $data = News::all();
        return ['data' => $data, 'code' => 1, 'message' => 'success'];
    }

    public function getAllTextNews()
    {
        $data = Db::table('news')->where('type', 1)->select();
        return ['data' => $data, 'code' => 1, 'message' => 'success'];
    }

    public function getAllVideoNews()
    {
        $data = Db::table('news')->where('type', 2)->select();
        return ['data' => $data, 'code' => 1, 'message' => 'success'];
    }

    public function getPageNews()
    {
        $page = file_get_contents("php://input");
        $start = ($page - 1) * 5;
        $data = Db::table('news')->limit($start, 5)->select();
        return ['data' => $data, 'code' => 1, 'message' => 'success'];
    }

    public function reGister()
    {
        $data = file_get_contents("php://input");
        $arrary = json_decode($data, true);
        $user = Db::table('user')->where('name', $arrary['name'])->find();
        if ($user == null) {
            $result = Db::table('user')->insert($arrary);
            if ($result == 1) {
                return ['data' => '', 'code' => 1, 'message' => 'success'];
            } else {
                return ['data' => '', 'code' => 2, 'message' => 'failure'];
            }
        } else {
            return ['data' => '', 'code' => 2, 'message' => '用户已经存在user exits'];
//  		return json_encode(['data'=>'','code'=>2,'message'=>'user exits']);
        }
    }

    public function logIn()
    {
        $data = file_get_contents("php://input");
        $arrary = json_decode($data, true);
        $user = Db::table('user')->where($arrary)->find();
        if ($user != null) {
            return ['data' => '', 'code' => 1, 'message' => 'success'];
        } else {
            return ['data' => '', 'code' => 2, 'message' => 'name or pass error!'];
        }
    }
}